# Generated by Django 5.2 on 2025-04-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AddField(
            model_name='volunteer',
            name='notification_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
