# Generated by Django 5.2 on 2025-04-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_alter_volunteer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='has_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
