# Generated by Django 5.2 on 2025-04-23 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_location_address_alter_location_name'),
        ('shifts', '0002_remove_position_max_volunteers_shift_max_volunteers'),
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='event',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='events.event'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PositionVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.position')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteer')),
            ],
            options={
                'unique_together': {('position', 'volunteer')},
            },
        ),
        migrations.AddField(
            model_name='position',
            name='volunteers',
            field=models.ManyToManyField(related_name='available_positions', through='shifts.PositionVolunteer', to='volunteers.volunteer'),
        ),
    ]
