# Generated by Django 5.2 on 2025-04-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_position_event_positionvolunteer_position_volunteers'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='color',
            field=models.CharField(choices=[('slate', 'Slate'), ('gray', 'Gray'), ('red', 'Red'), ('orange', 'Orange'), ('amber', 'Amber'), ('yellow', 'Yellow'), ('lime', 'Lime'), ('green', 'Green'), ('emerald', 'Emerald'), ('teal', 'Teal'), ('cyan', 'Cyan'), ('sky', 'Sky'), ('blue', 'Blue'), ('indigo', 'Indigo'), ('violet', 'Violet'), ('purple', 'Purple'), ('fuchsia', 'Fuchsia'), ('pink', 'Pink'), ('rose', 'Rose')], default='blue', help_text='Color theme for the position badge', max_length=20),
        ),
    ]
